/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import jdk.nashorn.internal.runtime.regexp.joni.EncodingHelper;

/**
 *
 * @author Bartosz
 */
public class Nauka extends javax.swing.JFrame {
    Okno dane;
    Random random= new Random();
    int wylosowanynumer;
    String odpowiedz;
   public static  Nauka nauka=new Nauka();
    /**
     * Creates new form Nauka
     */
    public Nauka()
    {
        initComponents();   
        
    }
    
    public Nauka(Okno Dane)
    {
        initComponents();
        dane=Dane;
        
        
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent ev) {
                dane.okno.setEnabled(true);
                dane.NaukaMenu.setEnabled(true);
                System.out.println("dfsgd");
                dispose();
            }
        });
        /*
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pytające okno");
        addWindowListener(new java.awt.event.WindowAdapter() {

            trzeba zrobic zamykanie sie jednego okna
          
            public void windowClosing(java.awt.event.WindowEvent evt) {
                 dane.okno.setEnabled(true);
                System.out.println("dfsgd");
                nauka
                
               
            }
        });
       */  

  
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PytanieLabel = new javax.swing.JLabel();
        OdpowiedzTextField = new javax.swing.JTextField();
        LosujButton = new javax.swing.JButton();
        Sprawdź = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        PytanieLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PytanieLabel.setText("Pytanie");

        OdpowiedzTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LosujButton.setText("Losuj Pytanie");
        LosujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LosujButtonActionPerformed(evt);
            }
        });

        Sprawdź.setText("Sprawdź");
        Sprawdź.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SprawdźActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PytanieLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OdpowiedzTextField))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LosujButton)
                .addGap(39, 39, 39)
                .addComponent(Sprawdź)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(PytanieLabel)
                .addGap(28, 28, 28)
                .addComponent(OdpowiedzTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LosujButton)
                    .addComponent(Sprawdź))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LosujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LosujButtonActionPerformed
       do   
       {
            wylosowanynumer=random.nextInt(dane.odpowiedzi.length);
       } while(dane.odpowiedzi[wylosowanynumer]==null || dane.pytania[wylosowanynumer]==null);
       PytanieLabel.setText(dane.pytania[wylosowanynumer]);
        
    }//GEN-LAST:event_LosujButtonActionPerformed

    private void SprawdźActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SprawdźActionPerformed
      odpowiedz= OdpowiedzTextField.getText();
      if(odpowiedz.equals(dane.odpowiedzi[wylosowanynumer]))
      {
                    JOptionPane.showMessageDialog(this,"tekst");

                    System.err.println("sadfs");
      }
    }//GEN-LAST:event_SprawdźActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nauka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nauka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nauka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nauka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nauka.setVisible(true);
            }
        });
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LosujButton;
    private javax.swing.JTextField OdpowiedzTextField;
    private javax.swing.JLabel PytanieLabel;
    private javax.swing.JButton Sprawdź;
    // End of variables declaration//GEN-END:variables
}
