/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bartosz
 */
public class Okno extends javax.swing.JFrame {
DefaultTableModel dtm ;
PrintWriter zapis;
int liczbawierszy;
public String [] odpowiedzi, pytania;
Scanner scanner;
FileReader odczyt;
int liczbaLinii=0;
protected static Okno okno= new Okno();
BufferedReader czytajTekst ;
Nauka nauka;
    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
        dtm = new DefaultTableModel(0, 0);
        String header[] = new String[] { "Pytanie", "Odpowiedz" };

// add header in table model     
        dtm.setColumnIdentifiers(header);
        Tabela.setModel(dtm);

     // add row dynamically into the table      
        for (int count = 1; count <= 10; count++) {
        dtm.addRow(new Object[] { "",""});
         }
jScrollPane2.setViewportView(Tabela);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        ImportujMenu = new javax.swing.JMenuItem();
        EksportujMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        NaukaMenu = new javax.swing.JMenuItem();
        TestMenu = new javax.swing.JMenuItem();
        DodajWierszeMenu = new javax.swing.JMenuItem();
        UsunWierszeMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NaukaSłówek");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabela);

        jMenu2.setText("Plik");

        ImportujMenu.setText("Importuj");
        ImportujMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportujMenuActionPerformed(evt);
            }
        });
        jMenu2.add(ImportujMenu);

        EksportujMenu.setText("Eksportuj");
        EksportujMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EksportujMenuActionPerformed(evt);
            }
        });
        jMenu2.add(EksportujMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opcje");

        NaukaMenu.setText("Nauka");
        NaukaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaukaMenuActionPerformed(evt);
            }
        });
        jMenu3.add(NaukaMenu);

        TestMenu.setText("Test");
        TestMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestMenuActionPerformed(evt);
            }
        });
        jMenu3.add(TestMenu);

        DodajWierszeMenu.setText("Dodaj wiersze");
        DodajWierszeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajWierszeMenuActionPerformed(evt);
            }
        });
        jMenu3.add(DodajWierszeMenu);

        UsunWierszeMenu.setText("Usun wiersze");
        UsunWierszeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunWierszeMenuActionPerformed(evt);
            }
        });
        jMenu3.add(UsunWierszeMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DodajWierszeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajWierszeMenuActionPerformed
        try
        {
        liczbawierszy= Integer.parseInt(JOptionPane.showInputDialog("podaj liczbę"));            
        }
        catch ( NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Nie podałeś liczby","Błąd Liczby",JOptionPane.ERROR_MESSAGE);
        }
            for(int i=0;i<liczbawierszy;i++ )
        dtm.addRow(new Object[] { null,null});
        
// TODO add your handling code here:
    }//GEN-LAST:event_DodajWierszeMenuActionPerformed

    private void UsunWierszeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunWierszeMenuActionPerformed
         try
            {
            liczbawierszy= Integer.parseInt(JOptionPane.showInputDialog("podaj liczbę"));            
            }
            catch ( NumberFormatException e)
            {
            JOptionPane.showMessageDialog(this, "Nie podałeś liczby","Błąd Liczby",JOptionPane.ERROR_MESSAGE);
            }
         for(int i=0;i<liczbawierszy;i++ )
             
            dtm.removeRow(dtm.getRowCount()-1);        // TODO add your handling code here:
    }//GEN-LAST:event_UsunWierszeMenuActionPerformed

    private void EksportujMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EksportujMenuActionPerformed

        odpowiedzi= new String[Tabela.getRowCount()];
        pytania= new String[Tabela.getRowCount()];

        for(int i=0;i<Tabela.getRowCount();i++)
        {
                pytania[i]=  (String) Tabela.getModel().getValueAt(i, 0);
                odpowiedzi[i]=  (String) Tabela.getModel().getValueAt(i, 1);

                System.out.println( odpowiedzi[i]+ "   " + pytania[i]);
               
            
        }
                 try {
        zapis = new PrintWriter("test.txt");
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Okno.class.getName()).log(Level.SEVERE, null, ex);
    }
                 for(int i=0; i<Tabela.getRowCount();i++)
                 {
                     zapis.println(pytania[i]);
                     zapis.println(odpowiedzi[i]);
                 }
                     
                 zapis.close();
                 
    }//GEN-LAST:event_EksportujMenuActionPerformed

    private void ImportujMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportujMenuActionPerformed
        liczbaLinii=0;
    try {                                             
        String tymczasowy;
        try {
            odczyt= new FileReader("test.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Okno.class.getName()).log(Level.SEVERE, null, ex);
        }
        czytajTekst= new BufferedReader(odczyt);
        while ( (tymczasowy=czytajTekst.readLine() ) != null ) {
      
            if(liczbaLinii/2>Tabela.getRowCount()-1 )
                dtm.addRow(new Object[] { null,null});
            if(liczbaLinii%2==0)
           // System.err.println(tymczasowy);
                Tabela.getModel().setValueAt(tymczasowy, liczbaLinii/2,0);
            else
               Tabela.getModel().setValueAt(tymczasowy, (liczbaLinii-1)/2,1); 
            liczbaLinii++;
            
        }
        System.out.println(liczbaLinii);
        
    } catch (IOException ex) {
        Logger.getLogger(Okno.class.getName()).log(Level.SEVERE, null, ex);
    }
    

    
        
    
  
    }//GEN-LAST:event_ImportujMenuActionPerformed

    
    private void wypelnienie()
    {
     
        
        odpowiedzi= new String[Tabela.getRowCount()];
        pytania= new String[Tabela.getRowCount()];
        
         for(int i=0;i<Tabela.getRowCount();i++)
        {
            if(Tabela.getModel().getValueAt(i, 0)!="" && Tabela.getModel().getValueAt(i, 1)!="")
            {
                        odpowiedzi[i]=(String) Tabela.getModel().getValueAt(i, 1);
                        pytania[i]=(String) Tabela.getModel().getValueAt(i, 0);

            }
        }
        
    }
    private void NaukaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaukaMenuActionPerformed
            
            wypelnienie();
            nauka= new Nauka(this);
            nauka.setVisible(true);     
            NaukaMenu.setEnabled(false);
            okno.setEnabled(false);
    }//GEN-LAST:event_NaukaMenuActionPerformed

    private void TestMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestMenuActionPerformed
JFileChooser jfc=new JFileChooser();
jfc.showDialog(null,"JakiśTamOpis");    
        System.err.println(jfc.getSelectedFile().getAbsolutePath());
// TODO add your handling code here:
    }//GEN-LAST:event_TestMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                okno.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DodajWierszeMenu;
    private javax.swing.JMenuItem EksportujMenu;
    private javax.swing.JMenuItem ImportujMenu;
    protected javax.swing.JMenuItem NaukaMenu;
    public javax.swing.JTable Tabela;
    private javax.swing.JMenuItem TestMenu;
    private javax.swing.JMenuItem UsunWierszeMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    protected javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
